version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/frontend"
    update_schedule: "daily"
    target_branch: "feature/react-frontend"
  - package_manager: "java:maven"
    directory: "/frontend"
    update_schedule: "weekly"
    target_branch: "feature/react-frontend"
  - package_manager: "java:maven"
    directory: "/backend"
    update_schedule: "weekly"
    target_branch: "feature/react-frontend"
